version: "3"

services:
  api:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
    container_name: APIUPW
    environment:
      - http_proxy
      - https_proxy
      - POSTGRES_HOST=postgredb
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - API_KEY_UPW=${API_KEY_UPW}
    volumes:
      - ./download:/usr/src/app/download
    command: "npm start"
    ports:
      - "${API_PORT}:8080"
      
  postgredb:
    image: postgres:12.3
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    container_name: postgres
    environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:5432'
