version: "3"

services:
  api:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
    container_name: APIUPW
    environment:
      - NODE_ENV=production
      - http_proxy
      - https_proxy
      - API_KEY_UPW=${API_KEY_UPW}
    volumes:
      - ./out:/usr/src/app/out/
    command: "npm start"
    ports:
      - "8080:8080"
      
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    environment:
      - http_proxy
      - https_proxy
      - CLUSTER_NAME=ezunpaywall
      - EZUNPAYWALL_ES_PUBLISH
      - EZUNPAYWALL_ES_NODE_NAME
      - EZUNPAYWALL_ES_DISCOVERY
      - EZUNPAYWALL_ES_DISCOVERY_TYPE
      - EZUNPAYWALL_ES_NODE_MASTER
      - EZUNPAYWALL_ES_NODE_DATA
      - EZUNPAYWALL_ES_NODE_INGEST
      - EZUNPAYWALL_ES_NODE_SEARCH_REMOTE
      - EZUNPAYWALL_ES_INITIAL_MASTER_NODES
      - EZUNPAYWALL_SMTP_HOST
      - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD}
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
      - "./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.1
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_PASSWORD
      - ELASTICSEARCH_USERNAME
      - SERVER_HOST
      - SERVER_PORT
      - THIS_HOST
      - ELASTICSEARCH_HOSTS="http://elastic:9200"
      - KIBANA_DEFAULTAPPID
    volumes:
      - "./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml"

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local