version: "3"

services:
  api:
    build:
      context: .
    container_name: APIUPW
    environment:
      - POSTGRES_HOST=postgredb
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    user: "node"
    working_dir: /app
    volumes:
      - ./:/app
    command: "npm run dev"
    ports:
      - "${API_PORT}:8080"
      
  postgredb:
    image: postgres:12.3
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    container_name: postgres
    environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:5432'
