version: "3"

services:
  api:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
    container_name: APIUPW
    environment:
      - NODE_ENV=production
      - http_proxy
      - https_proxy
      - API_KEY_UPW=${API_KEY_UPW}
    volumes:
      - ./out:/usr/src/app/out/
    command: "npm start"
    ports:
      - "8080:8080"
      
  es01:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
      environment:
        - node.name=es01
        - cluster.name=es-docker-cluster
        - discovery.type=single-node
  #      - discovery.seed_hosts=es02,es03
  #- cluster.initial_master_nodes=es01,es02,es03
      # - cluster.initial_master_nodes=es01
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - data01:/usr/share/elasticsearch/data
      ports:
        - 9200:9200

  kib01:
    image: docker.elastic.co/kibana/kibana:7.9.1
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local
     
