version: "3"

services:
  api:
    image: node:14.5.0
    container_name: APIUPW
    environment:
      - POSTGRES_HOST=postgredb
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    user: "node"
    working_dir: /app
    volumes:
      - ./:/app
    command: "npm run dev"
    ports:
      - "${API_PORT}:8080"
      
  postgredb:
    image: postgres:12.3
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    container_name: postgres
    environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:5432'

  dbmanager:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:  
      - "8081:80"
    depends_on: 
      - postgredb
